'use client';
import {useEffect,useRef,useState} from 'react';
import type {ImportPreview} from '@/lib/import-service';
export function ImportPanel({accountKey,onImported}:{accountKey:string;onImported:()=>void}){
 const [preview,setPreview]=useState<ImportPreview|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState('');const controller=useRef<AbortController|null>(null);
 useEffect(()=>()=>controller.current?.abort(),[accountKey]);
 async function call(body:unknown){controller.current?.abort();controller.current=new AbortController();const r=await fetch('/api/import',{method:'POST',headers:{'Content-Type':'application/json','X-Liubai-Account':accountKey},body:JSON.stringify(body),signal:controller.current.signal,redirect:'error'});const d=await r.json() as {error?:string;preview:ImportPreview;imported:number;pending:number};if(!r.ok)throw Error(d.error||'导入未确认，请保留原文件。');return d;}
 async function select(file:File|undefined){if(!file)return;setBusy(true);setError('');setResult('');setPreview(null);try{if(file.size>4*1024*1024)throw Error('导入文件过大，请分批导入。');const data=JSON.parse(await file.text());if(data.format!=='liubai-import-request'||data.version!==1||data.accountKey!==accountKey)throw Error('这份文件没有绑定当前账号。请重新生成迁移文件。');const d=await call({...data,action:'preview'});setPreview(d.preview)}catch(e){setError(e instanceof Error?e.message:'无法读取文件。')}finally{setBusy(false)}}
 async function apply(){if(!preview)return;setBusy(true);setError('');try{const d=await call({action:'apply',batchId:preview.id,accountKey});setResult(`已导入 ${d.imported} 项，${d.pending} 项留待确认。原本地库已保留。`);setPreview(null);onImported()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <details className="organizer-preferences"><summary>迁移本地任务</summary><p>选择本机生成的迁移文件。只导入任务，原文、偏好和旧历史不会顺带上传。</p><label className="field-label">迁移文件<input type="file" accept="application/json,.json" disabled={busy} onChange={e=>void select(e.target.files?.[0])}/></label>{preview&&<div><p>目标为当前账号。新增 {preview.additions.length} 项，重复候选 {preview.duplicates.length} 项，保留原样 {preview.unchanged.length} 项。</p>{preview.additions.length>0&&<details><summary>将新增的任务</summary><ul>{preview.additions.map(x=><li key={x.sourceTaskId}>{x.task.title}{x.task.done?'（已完成）':''}</li>)}</ul></details>}{preview.duplicates.length>0&&<details><summary>需要你判断的候选</summary><ul>{preview.duplicates.map(x=><li key={x.sourceTaskId}>{x.task.title}：{x.reason}</li>)}</ul></details>}<p className="field-help">若云端任务在预览后变化，本批次会停止；不会覆盖你刚刚的修改。</p><button className="primary" disabled={busy} onClick={()=>void apply()}>按这个预览迁移</button></div>}{error&&<p role="alert" className="settings-error">{error}</p>}{result&&<p role="status">{result}</p>}</details>;
}
