'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Inbox,Check,Clock3,ChevronDown,RefreshCw,Send,Settings2} from 'lucide-react';
import {QUADS} from '@/lib/tasks';
import {defaultProfile,type OrganizerState,type Change,type Profile} from '@/lib/organizer';
async function request<T=OrganizerState>(accountKey:string,signal:AbortSignal,body?:unknown):Promise<T>{let r:Response;try{r=await fetch('/api/organizer',{method:body?'POST':'GET',headers:{'X-Liubai-Account':accountKey,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,cache:'no-store',signal:AbortSignal.any([signal,AbortSignal.timeout(12000)])})}catch{if(signal.aborted)throw new DOMException('Canceled','AbortError');throw Error('暂时无法连接。请检查网络或本地服务是否启动，输入草稿已保留。')}if(!r.headers.get('content-type')?.includes('json'))throw Error(r.status===401||r.redirected?'请重新登录后再打开收件箱。':'服务暂时没有响应，请稍后重新连接。');const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error||'暂时无法连接，请稍后重试。');if((!body||'accountKey' in d)&&(!('accountKey' in d)||d.accountKey!==accountKey))throw Error('账号已切换，请重新连接。');return d as T;}
const date=(s:string|null)=>s?new Date(s).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}):'尚未检查';
function differences(c:Change){const before=c.before,after=c.after;const fields:[string,string,string][]=[];
 if(!before)return [['象限','',QUADS[after.quadrant].name],['计划日期','',after.due||'未排期'],['说明','',after.note||'无补充']];
 if(c.kind==='delete')return [['任务状态',before.done?'已完成':'待办','移除（保留历史）']];
 if(before.title!==after.title)fields.push(['任务名称',before.title,after.title]);
 if(before.due!==after.due)fields.push(['计划日期',before.due||'未排期',after.due||'未排期']);
 if((before.deadline||'')!==(after.deadline||''))fields.push(['截止日期',before.deadline||'未设置',after.deadline||'未设置']);
 if(before.urgencyMode!==after.urgencyMode)fields.push(['紧急程度',before.urgencyMode||'原手动安排',after.urgencyMode==='auto'?'跟随截止日期':after.urgencyMode==='manualUrgent'?'手动紧急':'手动不紧急']);
 if(before.quadrant!==after.quadrant)fields.push(['安排',QUADS[before.quadrant].name,QUADS[after.quadrant].name]);
 if(before.category!==after.category)fields.push(['分类',before.category,after.category]);
 if(before.done!==after.done)fields.push(['状态',before.done?'已完成':'待办',after.done?'已完成':'待办']);
 if(before.note!==after.note)fields.push(['说明',before.note||'无',after.note||'无']);
 if(JSON.stringify(before.subtasks)!==JSON.stringify(after.subtasks))fields.push(['小步骤',before.subtasks.map(s=>(s.done?'✓ ':'○ ')+s.title).join('；')||'无',after.subtasks.map(s=>(s.done?'✓ ':'○ ')+s.title).join('；')||'无']);return fields;
}
export function InboxView({onTasksChanged,accountKey,mode}:{onTasksChanged:()=>void;accountKey:string;mode:'local'|'cloud'}){
 const [data,setData]=useState<OrganizerState|null>(null),[text,setText]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[tab,setTab]=useState<'pending'|'history'>('pending'),[profile,setProfile]=useState<Profile>(defaultProfile),[profileRevision,setProfileRevision]=useState(0);
 const lifetime=useRef(new AbortController());const req=useCallback(async<T=OrganizerState,>(body?:unknown)=>{const signal=lifetime.current.signal;const d=await request<T>(accountKey,signal,body);if(signal.aborted)throw new DOMException('Canceled','AbortError');return d},[accountKey]);const draftKey='liubai-inbox-draft:'+accountKey;
 const loadRun=useRef(0);const attempted=useRef('');const id=useRef(''),lock=useRef(false),profileDirty=useRef(false);
 const load=useCallback(async(clearError=true)=>{if(lock.current)return;const run=++loadRun.current;try{const d=await req() as OrganizerState;if(run!==loadRun.current)return;setData(d);if(clearError)setError('');if(!profileDirty.current){setProfile(d.profile);setProfileRevision(d.profileRevision)}}catch(e){if((e as Error).name!=='AbortError')setError((e as Error).message)}},[req]);
 useEffect(()=>{lifetime.current=new AbortController();void load();try{const stored=sessionStorage.getItem(draftKey);if(stored){const saved=JSON.parse(stored);if(typeof saved.text==='string'){setText(saved.text);id.current=saved.id||'';attempted.current=saved.attempted||''}}}catch{}const timer=setInterval(()=>{if(document.visibilityState==='visible')void load(false)},15000);return()=>{clearInterval(timer);lifetime.current.abort()}},[load,draftKey]);
 function setInput(value:string){if(attempted.current&&value!==attempted.current){id.current=crypto.randomUUID();attempted.current=''}setText(value);if(!id.current)id.current=crypto.randomUUID();try{sessionStorage.setItem(draftKey,JSON.stringify({text:value,id:id.current,attempted:attempted.current}))}catch{}}
 async function submit(){if(lock.current||!text.trim())return;lock.current=true;loadRun.current++;setBusy(true);setError('');try{if(!id.current)id.current=crypto.randomUUID();attempted.current=text;try{sessionStorage.setItem(draftKey,JSON.stringify({text,id:id.current,attempted:text}))}catch{}await req({action:'submit',id:id.current,text});attempted.current='';setText('');id.current='';try{sessionStorage.removeItem(draftKey)}catch{}setNotice(mode==='cloud'?(data?.remoteGrant.enabled?'原文已保存到云端，等待下一次整理。':'原文已保存到云端；请在空间与数据中启用本账号整理。'):'原文已保存到本机，等待整理。');setTab('pending')}catch(e){if((e as Error).name!=='AbortError')setError((e as Error).message)}finally{lock.current=false;setBusy(false);void load(false)}}
 async function decide(c:Change,decision:'accept'|'dismiss'){if(lock.current)return;lock.current=true;loadRun.current++;setBusy(true);setError('');try{await req({action:'decide',id:c.id,decision});setNotice(decision==='accept'?'已采用建议':'已保留原样');onTasksChanged()}catch(e){if((e as Error).name!=='AbortError')setError((e as Error).message)}finally{lock.current=false;setBusy(false);void load(false)}}
 async function saveProfile(){if(lock.current)return;lock.current=true;loadRun.current++;setBusy(true);setError('');try{const r=await req<{revision:number}>({action:'profile',profile,revision:profileRevision});setProfileRevision(r.revision);profileDirty.current=false;setNotice('整理偏好已保存，下次整理时生效')}catch(e){if((e as Error).name!=='AbortError')setError((e as Error).message)}finally{lock.current=false;setBusy(false);void load(false)}}
 const pending=data?.entries.filter(e=>e.state==='pending')||[],reviews=data?.changes.filter(c=>c.state==='pending')||[];
 return <div className="inbox-view">
 <section className="capture-card"><label htmlFor="inbox-text">想到什么，先放在这里</label><p>整段粘贴，或用系统听写输入。日期、变化、犹豫的地方，都可以一起说。</p><textarea id="inbox-text" value={text} onChange={e=>setInput(e.target.value)} disabled={busy} maxLength={20000} rows={6} placeholder="比如：方案草稿已经写好，周五和同事讨论。这个月想整理照片，再安排一次短途出游……"/><div className="capture-actions"><span>先记下来，不必自己拆成任务。{text.length>18000&&` ${text.length}/20000`}</span><button className="primary" disabled={busy||!text.trim()||!data} onClick={()=>void submit()}><Send size={16}/>{busy?'正在保存…':'放入收件箱'}</button></div></section>
 <div className="organizer-status"><Clock3 size={15}/><span>{mode==='local'?'本地 Codex 整理':data?.remoteGrant.enabled?'云端收件箱 · 已授权整理':'云端收件箱 · 尚未启用整理'} · {data?.lastCheck?`最近检查 ${date(data.lastCheck)}`:'等待首次检查'}<small>{data?.lastResult||(mode==='cloud'?'网页保存后会在云端排队。Mac 和 Codex 在线时，每小时检查一次。':'等待本机整理。')}</small></span><button onClick={()=>void load()} aria-label="刷新收件箱" title="刷新收件箱"><RefreshCw size={16}/></button></div>
 {error&&<div className="inbox-message error" role="alert">{error}<button onClick={()=>void load()}>重新连接</button></div>}{notice&&<div className="inbox-message" role="status">{notice}<button onClick={()=>setNotice('')}>知道了</button></div>}
 <div className="inbox-tabs" role="tablist" aria-label="收件箱记录"><button role="tab" aria-selected={tab==='pending'} onClick={()=>setTab('pending')}>待处理{pending.length+reviews.length>0&&<span>{pending.length+reviews.length}</span>}</button><button role="tab" aria-selected={tab==='history'} onClick={()=>setTab('history')}>整理记录</button></div>
 {tab==='pending'?<div className="inbox-stack">
 {reviews.length>0&&<h2 className="inbox-section-title">有几处，想听听你的判断</h2>}
 {reviews.map(c=><article className="review-card" key={c.id}><header><span className="review-label">{c.kind==='create'?'确认新增':c.kind==='delete'?'确认移除':'确认调整'}</span><h3>{c.after.title}</h3></header><p>{c.reason}</p><dl className="change-diff">{differences(c).map(([label,from,to])=><div key={label}><dt>{label}</dt><dd>{from&&<span className="before-value">{from}</span>}<span>{to}</span></dd></div>)}</dl><div className="review-actions"><button className="text-button" disabled={busy} onClick={()=>void decide(c,'dismiss')}>保留原样</button><button className="primary" disabled={busy} onClick={()=>void decide(c,'accept')}><Check size={15}/>采用建议</button></div></article>)}
 {pending.map(e=><article className="entry-card" key={e.id}><header><span><Clock3 size={14}/>等待整理</span><time>{date(e.created_at)}</time></header><p className="raw-input">{e.body}</p></article>)}
 {!pending.length&&!reviews.length&&<div className="inbox-empty"><Inbox size={30}/><h2>这里没有需要操心的事</h2><p>新的想法放在上面，整理完会各归其位。</p></div>}
 </div>:<div className="inbox-stack">{data?.entries.filter(e=>e.state==='processed').map(e=><article className="entry-card" key={e.id}><header><span><Check size={15}/>已整理</span><time>{date(e.processed_at)}</time></header><p>{e.summary}</p><div className="entry-results">{data.changes.filter(c=>c.entry_id===e.id).map(c=><div key={c.id}><span>{c.state==='applied'?'已应用':c.state==='dismissed'?'保留原样':'待确认'}</span>{c.after.title}</div>)}</div><details><summary>查看原始输入</summary><p className="raw-input">{e.body}</p></details></article>)}{!data?.entries.some(e=>e.state==='processed')&&<p className="inbox-empty">整理后，原文与变更记录会保留在这里。</p>}</div>}
 <details className="organizer-preferences"><summary><Settings2 size={17}/>我的整理习惯<ChevronDown size={16}/></summary><p>这些是你可以查看、修改的偏好；不会根据几条任务猜测你的性格。</p><label className="field-label">当前工作背景<textarea rows={2} maxLength={2000} value={profile.about} onChange={e=>{profileDirty.current=true;setProfile({...profile,about:e.target.value})}} placeholder="例如：研究、论文返修、助教工作并行"/></label><label className="field-label">希望怎样帮你整理<textarea rows={4} maxLength={4000} value={profile.preferences} onChange={e=>{profileDirty.current=true;setProfile({...profile,preferences:e.target.value})}}/></label><label className="filter-check"><input type="checkbox" checked={profile.autoSafe} onChange={e=>{profileDirty.current=true;setProfile({...profile,autoSafe:e.target.checked})}}/>明确新增、追加说明和步骤，可自动保存</label><p className="field-help">日期、象限、完成状态、删除与覆盖已有内容仍需确认；关掉后，所有建议都由你确认。未再提及的任务会保留。</p><div className="review-actions"><button className="text-button" onClick={()=>{profileDirty.current=false;void load()}}>重新载入</button><button className="primary" disabled={busy||!data} onClick={()=>void saveProfile()}>保存偏好</button></div></details>
 </div>;
}
