import {sqliteTable,text,integer,primaryKey,index} from 'drizzle-orm/sqlite-core';
export const tasks=sqliteTable('tasks',{id:text('id').notNull(),owner:text('owner').notNull(),data:text('data').notNull(),revision:integer('revision').notNull().default(0),deleted:integer('deleted').notNull().default(0)},t=>[primaryKey({columns:[t.owner,t.id]}),index('idx_tasks_owner_deleted').on(t.owner,t.deleted)]);
export const spaces=sqliteTable('spaces',{owner:text('owner').primaryKey(),initialized:integer('initialized').notNull().default(1)});
export const inboxEntries=sqliteTable('inbox_entries',{owner:text('owner').notNull(),id:text('id').notNull(),body:text('body').notNull(),state:text('state').notNull().default('pending'),summary:text('summary').notNull().default(''),planToken:text('plan_token'),createdAt:text('created_at').notNull(),processedAt:text('processed_at')},t=>[primaryKey({columns:[t.owner,t.id]}),index('idx_inbox_owner_state').on(t.owner,t.state)]);
export const taskChanges=sqliteTable('task_changes',{owner:text('owner').notNull(),id:text('id').notNull(),entryId:text('entry_id').notNull(),kind:text('kind').notNull(),before:text('before_data'),after:text('after_data').notNull(),reason:text('reason').notNull(),automatic:integer('automatic').notNull().default(0),state:text('state').notNull().default('pending'),createdAt:text('created_at').notNull(),decidedAt:text('decided_at')},t=>[primaryKey({columns:[t.owner,t.id]}),index('idx_changes_owner_entry').on(t.owner,t.entryId),index('idx_changes_owner_state').on(t.owner,t.state)]);
export const organizerProfiles=sqliteTable('organizer_profiles',{owner:text('owner').primaryKey(),data:text('data').notNull(),revision:integer('revision').notNull().default(0),lastCheck:text('last_check'),lastResult:text('last_result').notNull().default('尚未检查')});
export const organizerGrants=sqliteTable('organizer_grants',{owner:text('owner').primaryKey(),accountKey:text('account_key').notNull().unique(),enabled:integer('enabled').notNull().default(0),backupEnabled:integer('backup_enabled').notNull().default(0),generation:integer('generation').notNull().default(0),updatedAt:text('updated_at').notNull()});
export const agentJobs=sqliteTable('agent_jobs',{id:text('id').primaryKey(),owner:text('owner').notNull(),requestId:text('request_id').notNull(),generation:integer('generation').notNull(),tokenHash:text('token_hash').notNull(),leaseUntil:text('lease_until').notNull(),state:text('state').notNull().default('leased'),createdAt:text('created_at').notNull(),finishedAt:text('finished_at'),result:text('result').notNull().default('')},t=>[index('idx_jobs_owner_state').on(t.owner,t.state),index('idx_jobs_owner_request').on(t.owner,t.requestId)]);

export const taskImports=sqliteTable('task_imports',{owner:text('owner').notNull(),id:text('id').notNull(),data:text('data').notNull(),state:text('state').notNull().default('preview'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[primaryKey({columns:[t.owner,t.id]})]);
