import {z} from 'zod';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {database} from '@/lib/database';
import {accountKey,assertAccount} from '@/lib/account';
import {sampleTasks} from '@/lib/tasks';
import {defaultProfile,profileSchema} from '@/lib/organizer';
export const dynamic='force-dynamic';
import {dateSchema as date,taskSchema} from '@/lib/task-schema';
const response=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
export async function GET(){try{const u=await getChatGPTUser();if(!u)return response({error:'登录已过期，请重新登录后继续。',code:'AUTH_REQUIRED'},401);const db=database();const [rows,space,profile]=await db.batch([db.prepare('SELECT data, revision FROM tasks WHERE owner = ? AND deleted = 0').bind(u.userId),db.prepare('SELECT initialized FROM spaces WHERE owner = ?').bind(u.userId),db.prepare('SELECT data FROM organizer_profiles WHERE owner = ?').bind(u.userId)]);const saved=(profile.results[0] as {data:string}|undefined),prefs=profileSchema.parse(saved?JSON.parse(saved.data):defaultProfile);return response({tasks:(rows.results as {data:string;revision:number}[]).map(r=>({...JSON.parse(r.data),revision:r.revision})),initialized:!!space.results[0],urgencyPreferences:{urgentDays:prefs.urgentDays,timezone:prefs.timezone},account:{key:await accountKey(u.userId),name:u.displayName,mode:u.local?'local':'cloud'}});}catch(e){console.error('task load',String(e),e instanceof Error?String(e.cause):'');return response({error:'任务存储暂时不可用。你仍可以先写下任务，连接恢复后再保存。',code:'STORAGE_UNAVAILABLE'},503);}}
export async function POST(request:Request){try{const origin=request.headers.get('origin');if(origin&&new URL(origin).host!==new URL(request.url).host)return response({error:'请求来源不匹配，请从留白页面重新打开'},403);const u=await getChatGPTUser();if(!u)return response({error:'请先登录。'},401);await assertAccount(request,u.userId);const db=database();const body=z.record(z.unknown()).parse(await request.json());if(body.action==='initialize'){const today=date.parse(body.today);if(!today)return response({error:'日期不能为空'},400);const samples=body.samples===true?sampleTasks(today):[];await db.batch([...samples.map(t=>db.prepare('INSERT OR IGNORE INTO tasks (owner,id,data,revision,deleted) SELECT ?,?,?,0,0 WHERE NOT EXISTS (SELECT 1 FROM spaces WHERE owner = ?)').bind(u.userId,t.id,JSON.stringify(t),u.userId)),db.prepare('INSERT OR IGNORE INTO spaces (owner,initialized) VALUES (?,1)').bind(u.userId)]);return GET();}
if(body.action==='delete'){const id=z.string().min(1).max(100).parse(body.id);const revision=z.number().int().min(0).parse(body.revision);const result=await db.prepare('UPDATE tasks SET deleted = 1, revision = revision + 1 WHERE owner = ? AND id = ? AND revision = ? AND deleted = 0').bind(u.userId,id,revision).run();if(!result.meta.changes){const current=await db.prepare('SELECT revision,deleted FROM tasks WHERE owner = ? AND id = ?').bind(u.userId,id).first<{revision:number;deleted:number}>();if(current?.deleted===1&&current.revision===revision+1)return response({revision:revision+1});return response({error:'任务已在其他页面更新。请刷新后重试。'},409);}return response({revision:revision+1});}
if(body.action==='restore'){const id=z.string().min(1).max(100).parse(body.id),revision=z.number().int().min(0).parse(body.revision);const current=await db.prepare('SELECT data,revision,deleted FROM tasks WHERE owner = ? AND id = ?').bind(u.userId,id).first<{data:string;revision:number;deleted:number}>();if(current?.deleted===0&&current.revision===revision+1)return response({task:{...JSON.parse(current.data),revision:current.revision}});if(!current||!current.deleted||current.revision!==revision)return response({error:'任务已变化，请重新连接后查看。',code:'CONFLICT'},409);const restored={...JSON.parse(current.data),revision:revision+1};const result=await db.prepare('UPDATE tasks SET deleted = 0, data = ?, revision = revision + 1 WHERE owner = ? AND id = ? AND revision = ? AND deleted = 1').bind(JSON.stringify(restored),u.userId,id,revision).run();if(!result.meta.changes){const checked=await db.prepare('SELECT data,revision,deleted FROM tasks WHERE owner = ? AND id = ?').bind(u.userId,id).first<{data:string;revision:number;deleted:number}>();if(checked?.deleted===0&&checked.revision===restored.revision&&checked.data===JSON.stringify(restored))return response({task:restored});return response({error:'任务已变化，请重新连接后查看。',code:'CONFLICT'},409);}return response({task:restored});}
const task=taskSchema.parse(body.task);if(task.done)task.subtasks=task.subtasks.map(s=>({...s,done:true}));if(body.action==='create'){const results=await db.batch([db.prepare('INSERT OR IGNORE INTO spaces (owner,initialized) VALUES (?,1)').bind(u.userId),db.prepare('INSERT OR IGNORE INTO tasks (owner,id,data,revision,deleted) VALUES (?,?,?,0,0)').bind(u.userId,task.id,JSON.stringify(task))]);if(!results[1].meta.changes){const existing=await db.prepare('SELECT data,revision,deleted FROM tasks WHERE owner = ? AND id = ?').bind(u.userId,task.id).first<{data:string;revision:number;deleted:number}>();if(existing&&!existing.deleted&&existing.revision===0&&existing.data===JSON.stringify(task))return response({task:{...task,revision:0}});return response({error:'这项任务已存在，请重新连接查看。',code:'CONFLICT'},409);}return response({task:{...task,revision:0}});}
if(body.action!=='update')return response({error:'未知操作'},400);const next={...task,revision:task.revision+1};const result=await db.prepare('UPDATE tasks SET data = ?, revision = revision + 1 WHERE owner = ? AND id = ? AND revision = ? AND deleted = 0').bind(JSON.stringify(next),u.userId,task.id,task.revision).run();if(!result.meta.changes){const current=await db.prepare('SELECT data,revision,deleted FROM tasks WHERE owner = ? AND id = ?').bind(u.userId,task.id).first<{data:string;revision:number;deleted:number}>();if(current&&!current.deleted&&current.revision===next.revision&&current.data===JSON.stringify(next))return response({task:next});return response({error:'任务已在其他页面更新。请先重新连接，保留你的修改后再合并。',code:'CONFLICT'},409);}return response({task:next});
}catch(e){if(e instanceof Error&&'status' in e)return response({error:e.message,code:'code' in e?String(e.code):undefined},Number(e.status));if(e instanceof z.ZodError||e instanceof SyntaxError)return response({error:'请检查任务名称、日期与子任务内容。'},400);console.error('task save',e);return response({error:'保存未确认，请保留内容并重试。'},503);}}
